import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  ignoreNoDocuments: true,
  schema: [
    {
      [`https://api-us-east-1-shared-usea1-02.hygraph.com/v2/${process.env.CMS_SPACE}/${process.env.CMS_ENV}`]:
        {
          headers: {
            // Authorization: `Bearer ${process.env.CMS_PROD_TOKEN!}`,
          },
        },
    },
  ],
  documents: [
    'src/**/*.tsx',
    'src/**/*.ts',
    '!node_modules',
    '!src/graphql/**/*',
  ],
  generates: {
    'src/app/_graphql/generated/types.generated.ts': {
      config: {
        avoidOptionals: true,
        skipTypename: true,
      },
      plugins: [
        {
          add: {
            content: `// DO NOT EDIT
        // This file is automatically generated, run yarn gen to update
                `,
          },
        },
        'typescript',
        'typescript-operations',
      ],
    },
    './schema.generated.graphql': {
      plugins: ['schema-ast'],
    },
  },
};

export default config;
