import clsx from 'clsx';
import { Header } from './_components/common/Header';
import { fontManrope, fontPlexMono } from './_styles/fonts';
import './_styles/globals.css';

export const metadata = {
  title: 'Westley Ferguson',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(fontManrope.variable, fontPlexMono.variable, 'bg-sand')}
      >
        <div className="max-w-[1920px] mx-auto px-5 md:pr-20 pt-4 pb-12 xl:pr-36 leading-tight">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
